### ISSUE TITLE
Exception when bluetoothAdapter.listenUsingRfcommWithServiceRecord on KK 4.4.2

### ISSUE THREAD

**Issue by veiz** [giladHaimov/BTWiz#1]
Hi, I met this crash when use your test code `createBTServerSocket` function on KK / MTK phone, did you code compatible with that? 

Here's the logcat (filtered):

``` log
01-01 00:11:16.873 1858-1858/com.yuan.diagnostic D/BluetoothAdapter: isEnabled
01-01 00:11:16.951 1858-1878/com.yuan.diagnostic D/BluetoothAdapter: getAddress
01-01 00:11:16.961 1858-1878/com.yuan.diagnostic W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
01-01 00:12:05.262 1858-1878/com.yuan.diagnostic E/BluetoothSocket: java.lang.Throwable
                                                                        at android.bluetooth.BluetoothSocket.bindListen(BluetoothSocket.java:355)
                                                                        at android.bluetooth.BluetoothAdapter.createNewRfcommSocketAndRecord(BluetoothAdapter.java:1069)
                                                                        at android.bluetooth.BluetoothAdapter.listenUsingRfcommWithServiceRecord(BluetoothAdapter.java:990)
                                                                        at com.btwiz.library.BTWiz.createBTServerSocket(BTWiz.java:493)
                                                                        at com.btwiz.library.BTWiz$2.run(BTWiz.java:433)
01-01 00:12:05.266 1858-1878/com.yuan.diagnostic W/System.err:     at android.bluetooth.BluetoothAdapter.createNewRfcommSocketAndRecord(BluetoothAdapter.java:1074)
01-01 00:12:05.268 1858-1878/com.yuan.diagnostic W/System.err:     at android.bluetooth.BluetoothAdapter.listenUsingRfcommWithServiceRecord(BluetoothAdapter.java:990)
01-01 00:12:05.293 1858-1871/com.yuan.diagnostic D/BluetoothAdapter: onBluetoothServiceDown: android.bluetooth.IBluetooth$Stub$Proxy@41eef250
01-01 00:12:05.887 1858-1870/com.yuan.diagnostic D/BluetoothAdapter: onBluetoothServiceUp: android.bluetooth.IBluetooth$Stub$Proxy@41f2b0f8
```

**Comment by giladHaimov** [comment]
Greeting Wei

Apparently this is a know issue on some devices.

See suggested solution here:
http://stackoverflow.com/questions/8215108/bluetooth-issues-on-htc-hero/8273159#8273159

To keep you from a long wait I suggest u will try adding the above fix directly to BTWiz code.

Let me know if it works for you.

Gilad
